### ISSUE TITLE
LocalDateTime for current timestamp in any format

### ISSUE THREAD

**Issue by albertosipov** [authorjapps/zerocode#33] opened 2018-02-15 17:29 UTC
@authorjapps , can you please support LocalDateTime for generating current timestamp which can be useful during test run?
e.g.
- For generating current timestamp in a format supplied at the runtime of tests
- For generating a random number using `datetime with milli of the day` or `datetime with nano of the day`
- Or simply print the date or year etc

**Comment by authorjapps** [comment] 2018-02-15 23:03
@albertosipov , This sounds like duplicate of https://github.com/authorjapps/zerocode/issues/29 related to LOCAL.DATE.TODAY. Please click and see, this have been answered for LOCAL.DATETIME.NOW https://github.com/authorjapps/zerocode/issues/29

**Closed** 2018-04-09 21:03 UTC
Labels: duplicate, fixed-and-released, good first issue
