### ISSUE TITLE
Generating Current Timestamp with microsecond with "SSSSSS" - Works but with padding three zeroes

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#658] opened 2024-04-08 15:03 UTC
Actual
===
```
"timeNow":"${LOCAL.DATETIME.NOW:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}Z"
Generates:
“2023-12-06T14:17:47.738000” 🔴  <— Always generates with “000” padding, which is not exactly correct
```

```
"timeNow":"${LOCAL.DATETIME.NOW:yyyy-MM-dd'T'HH:mm:ss.nnnnnnnnn}Z”
“2023-12-06T14:17:47.738553101” 🟢  <— works as expected.
```

Expected
===
```
"timeNow":"${LOCAL.DATETIME.NOW:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}Z"
Should generates:
“2023-12-06T14:17:47.738109” 
Or
“2023-12-06T14:17:47.738125” 
Or
“2023-12-06T14:17:47.738775”
Etc
```

- - - - 

Potential Fix
===
- If java8 has no outofthebox date/time function to generate this, then another PH(placeholder)-Token could be implemented to solve this.
- Or suggest any other idea 💡

**Comment by abhija77** [comment] 2024-05-02 09:35
Hi,

I would like to contribute to your project, to gain in experience.
How can i take this issue :) ?

Ayoub

**Comment by nirmalchandra** [comment] 2024-05-02 15:34
> Hi,
> 
> I would like to contribute to your project, to gain in experience. How can i take this issue :) ?
> 
> Ayoub

@abhija77 👋 , can you have a look at the [CONTRIBUTING](https://github.com/authorjapps/zerocode/blob/master/CONTRIBUTING.md) and [BUILDING](https://github.com/authorjapps/zerocode/blob/master/BUILDING.md) please.
That should give you some start point to crack on.

**Comment by brian6484** [comment] 2024-05-22 14:52
Hello :) I am new to open source contribution and came across this issue, which I would like to solve. But I just have a few questions.
1) What test do I need to run to see this timeNow field being printed out in the log? I ran a couple of tests but I dont see this timeNow field in the response body. Or will it help if I look at the documentation more closely?

2) I am thinking of using Java 8's DateTimeFormatter to format this like

```java
DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'");
return LocalDateTime.now().format(formatter);
```
Is this idea viable?

**Comment by luke-zhou** [comment] 2024-05-31 08:04
I think this is the issue with Java 8, the `LocalDateTime` is actually returning the `clock` value, which in Java 8 is based on `System.currentTimeMillis()`(in most operating system), and this is the reason it only returns 3 digits. 
and also, when I was testing:
```
"timeNow":"${LOCAL.DATETIME.NOW:yyyy-MM-dd'T'HH:mm:ss.nnnnnnnnn}Z”
“2024-05-31T17:29:06.979000000” 🟢  <— This return is different from yours, I dont know if I missed anything here.
```

I'm also uncertain if this level of accuracy is necessary. Since the value is used for comparison with API returns, the nanoseconds (and even milliseconds) might not align with the actual return values. To me, this seems unnecessary.

This is just my perspective, and I could be mistaken.

Cheers,



> # Actual
> ```
> "timeNow":"${LOCAL.DATETIME.NOW:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}Z"
> Generates:
> “2023-12-06T14:17:47.738000” 🔴  <— Always generates with “000” padding, which is not exactly correct
> ```
> 
> ```
> "timeNow":"${LOCAL.DATETIME.NOW:yyyy-MM-dd'T'HH:mm:ss.nnnnnnnnn}Z”
> “2023-12-06T14:17:47.738553101” 🟢  <— works as expected.
> ```
> 
> # Expected
> ```
> "timeNow":"${LOCAL.DATETIME.NOW:yyyy-MM-dd'T'HH:mm:ss.SSSSSS}Z"
> Should generates:
> “2023-12-06T14:17:47.738109” 
> Or
> “2023-12-06T14:17:47.738125” 
> Or
> “2023-12-06T14:17:47.738775”
> Etc
> ```
> 
> # Potential Fix
> * If java8 has no outofthebox date/time function to generate this, then another PH(placeholder)-Token could be implemented to solve this.
> * Or suggest any other idea 💡

**Comment by VinayMaurya001** [comment] 2024-06-09 14:04
Please add more details about the branch/files where the issue is!

**Comment by nirmalchandra** [comment] 2024-06-10 16:52
I think we can close this issue.

As you suggested, we can get almost the same result by this:
Instead of `"timeNow":"...'HH:mm:ss.SSSSSS}Z"`, the below can be used to get all the digits populated:
>"timeNow":"...'HH:mm:ss.SSS}123Z"

(... SSS}123 or SSS}456 etc... where SSS will resolve to random timelapsed mili-sec always and
then,  123 or 456 will be static, but together the whole number will be a random and unique and can be treated like nano-sec)

**Comment by anmol797** [comment] 2024-06-19 21:09
But then why to use 123 , we can use any random number , generated using (int) (Math.random() * 999) + 1

**Comment by nirmalchandra** [comment] 2024-06-22 18:32
> But then why to use 123 , we can use any random number , generated using (int) (Math.random() * 999) + 1

Good thought.
But does this works out of the box, not sure ? Give it a try!
```
(int) (Math.random() * 999) + 1
```

Probably not straight away as it has got `Math.random()` java language specific expression here.

Then to solve this you can pick the value from an earlier step by calling a static method if that helps.
But I would prefer to  go with `nnn123` as the `nnn` is still random 😄

**Comment by authorjapps** [comment] 2024-07-08 12:57
Add documentation with some examples

**Closed** 2024-07-08 12:57 UTC
Labels: good first issue
