### ISSUE TITLE
Sending raw string in urlencoded data field #question

### ISSUE THREAD

**Issue by automatedbegginer** [authorjapps/zerocode#331] opened 2019-10-24 15:04 UTC
Hello,

I have the following data to send:

      "name": "post_message",
      "url": "some/url",
      "operation": "POST",
      "request": {
        "headers": {
          "Content-Type": "application/x-www-form-urlencoded"
        },
        "body": {
          "id": "84844",
          "data": "SOME*DATA\nMORE*DATA",
        }
      }

When I follow TCP stream, in request I get encoded data "data=SOME*DATA%5CnMORE&id=84844".

1. Is there any way to send raw data in this field without encoding?
2. Is there any way to preserve parameter ordering (id&data instead of data&id)?

**Comment by authorjapps** [comment] 2019-10-26 10:21
Hello @automatedbegginer , 

> "data=SOME*DATA%5CnMORE&id=84844"

I believe the `Apache Http client` encodes this, the framework doesn't encode.

@arunvelusamyd , can you put some thought to this, please? You have dealt with quite a lot of realtime use cases(those definitely might help). Appreciate your help mate!

**Comment by sparrowV** [comment] 2020-05-04 13:27
@automatedbegginer  I think when you use `x-www-form-urlencoded` the body is automatically encoded as in case of url. maybe try `application/json` ? 
@authorjapps  is this issue still relevant?

**Comment by authorjapps** [comment] 2020-07-29 09:17
Thanks @sparrowV .
@automatedbegginer, can you reply ?

**Comment by automatedbegginer** [comment] 2020-07-29 09:37
Hi, i needed to use x-www-form-urlencoded to simulate messages between two apps. They send eachother x-www-form-urlencoded data, not json. I dont know any more details, since the issue is few months old :)

**Comment by nirmalchandra** [comment] 2023-04-16 20:40
Looks like a Duplicate of https://github.com/authorjapps/zerocode/issues/141

Reopen if it's not the case.

**Closed** 2023-04-16 20:40 UTC
Labels: question, answered
